### ISSUE TITLE
Remove redundant hero name from the sound warning

### ISSUE THREAD

**Issue by Jonarzz** [Jonarzz/DotaResponsesRedditBot#11]

**Comment by FlorianWendelborn** [comment]
What's redundant about it?

**Comment by Jonarzz** [comment]
Now the hero image (flair) is shown before the response, so the hero name is redundant (as reported by users).

**Comment by FlorianWendelborn** [comment]
Yes, but I think they don't consider mobile users. AFAIK most mobile clients don't support flairs. To save space I'd therefore suggest you to just shorten the hero names to AA, SD, SF, etc.. You could use what that dotamatch bot uses for dotabuff links.

**Comment by Jonarzz** [comment]
You're right about the mobile users. I think it's best to leave it as it is now. I thought that the flairs would be replaced with text if I typed it in, but it seems that it doesn't work that way. Thanks for pointing that out!
