### ISSUE TITLE
Improvement For One Of My Favorites

### ISSUE THREAD

**Issue by FlorianWendelborn** [Jonarzz/DotaResponsesRedditBot#12]
via [Reddit](https://www.reddit.com/r/DotA2/comments/4koxfo/my_new_little_comic_about_lycan_vs_beastmaster/d3grq3j?context=10000)

**Comment by Jonarzz** [comment]
Done: https://www.reddit.com/r/DotA2/comments/4koxfo/my_new_little_comic_about_lycan_vs_beastmaster/d3gvh7s
