### ISSUE TITLE
Prioritize hero lines over voice pack lines.

### ISSUE THREAD

**Issue by txdv** [Jonarzz/DotaResponsesRedditBot#13]
https://www.reddit.com/r/DotA2/comments/4ksc24/bro_shes_not_the_right_one_for_you/d3hpddh

Practice makes perfect! is a line by Clockwerk, it is also a line by the Bastion voice pack.

IMO it should prioritize Clockwerks line over Bastions voice pack.

**Comment by Jonarzz** [comment]
[Done.](https://www.reddit.com/r/DotA2/comments/4lr4p5/for_people_having_rough_times_with_quest_timers/d3pgoah)

("That's the spirit" was also read as Bastion Announcer's response)
