### ISSUE TITLE
Suggestion about sniper

### ISSUE THREAD

**Issue by gwtjxyz** [Jonarzz/DotaResponsesRedditBot#15]
So the other day ~~I found a cool idea on Reddit~~ came up with something absolutely brilliant. Make it so that the HO HO HA HA line has (Trigger warning: Sniper) instead of (Sound warning: Sniper). Could even have that on some other lines, but that's up to you. I wouldn't however advise you to have ALL the lines have a Trigger warning, because that would not be cool imo.

pls mr jonarz

**Comment by Jonarzz** [comment]
https://www.reddit.com/r/DotA2/comments/4rzfnt/upgrade_aghanim_scepter_fix_part_1/d55d0km
