### ISSUE TITLE
haHAA response for Monkey King

### ISSUE THREAD

**Issue by RasmusHansson** [Jonarzz/DotaResponsesRedditBot#20]
Pls for the memes

**Comment by Schipunov** [comment]
https://hydra-media.cursecdn.com/dota2.gamepedia.com/3/35/Monkey_ability1_12.mp3  
  
here

**Comment by OmNomNom3154** [comment]
I believe Jonarzz did implement a similar feature (trigger words like "dank", "your/ur brother", etc.) but it was ill-received by the /r/dota2 community. I doubt a feature like this would make a comeback (the response "ha ha" was also in the EXCLUDED_RESPONSE list).
