### ISSUE TITLE
This quotation: "We outnumbered you. We outnumber them all!" isn't picked up by the bot

### ISSUE THREAD

**Issue by fireattack** [Jonarzz/DotaResponsesRedditBot#21]
https://www.reddit.com/r/DotA2/comments/5y36pc/i_feel_like_this_is_intentional/demzcpq/?utm_content=permalink&utm_medium=front&utm_source=reddit&utm_name=DotA2

Quoting: "We outnumbered you. We outnumber them all!" Seems totally the same as the one in [Dota2Wiki](http://dota2.gamepedia.com/Phantom_Lancer/Responses).

**Comment by Jonarzz** [comment]
Fixed: https://www.reddit.com/r/DotA2/comments/8199fe/russia_region_lock/dv1gcms/
