### ISSUE TITLE
Lots of audio file links don't work any more

### ISSUE THREAD

**Issue by fireattack** [Jonarzz/DotaResponsesRedditBot#22]
Such as:

* https://www.reddit.com/r/DotA2/comments/80r2d7/whats_your_favorite_dota_2_hero_response/duxyneh/
* https://www.reddit.com/r/DotA2/comments/80r2d7/whats_your_favorite_dota_2_hero_response/duxyk1j/
* https://www.reddit.com/r/DotA2/comments/80rofc/apparently_the_strongest_na_team_is_actually_in/duxyj2t/

etc.

The link on Dota2Wiki seems to be changed to a CDN-sytle one, for example,

https://dota2.gamepedia.com/File:Chaknight_ability_phantasm_03.mp3

The file is https://d1u5p3l4wpay3k.cloudfront.net/dota2_gamepedia/2/28/Chaknight_ability_phantasm_03.mp3

**Comment by Jonarzz** [comment]
Thanks for reporting it! Seems to be fixed now:
https://www.reddit.com/r/DotA2/comments/818nxu/when_icefrog_doesnt_nerf_you/dv1f19t/
https://www.reddit.com/r/DotA2/comments/818bhb/dota_2_update_main_client_march_1_2018/dv1flls
https://www.reddit.com/r/DotA2/comments/818bhb/dota_2_update_main_client_march_1_2018/dv1fl81

**Comment by Jonarzz** [comment]
As observed by the users, other links are becaming unavailable. The links are being moved to another location in packs, after all of them are moved, I will run the script to update the database once more.
