### ISSUE TITLE
Wrong hero icon in some responses

### ISSUE THREAD

**Issue by TheGuywithTheHat** [Jonarzz/DotaResponsesRedditBot#23]
e.g. [here](https://www.reddit.com/r/DotA2/comments/83x126/so_i_cannot_see_even_the_most_basic_stats_for/dvl78da/) and [here](https://www.reddit.com/r/DotA2/comments/83zl59/cant_disjoint_attack_projectiles_since_dota_plus/dvlwie9/).

**Comment by Mysame** [comment]
https://www.reddit.com/r/DotA2/comments/8f2s2r/dota_714/dy01ptd/

Both heroes have the same voiceline

**Comment by luxalpa** [comment]
The issue still persists. After looking over the code (sorry I'm not very experienced in python), I figured that it could have been this line:

https://github.com/Jonarzz/DotaResponsesRedditBot/blob/ab3a1a6d5c9562d5845e099ede39b94c81169558/dota_responses_database.py#L45

Which probably messed up the database. :<

If the database contains multiple rows with the same response but with a different link, the query above will likely change those links to all be the same; however the hero-id's are not being adjusted, so the function that retrieves the data to render the content gets the `hero-id` for the picture while it takes the `link` for the name and - well - the link.

From what I've seen it's the only part in this code that could cause such a discrepancy, but I may be wrong.

**Comment by Jonarzz** [comment]
Closing the issue since the new Reddit looks do not support flairs (at least I did not see them on the Dota 2 subreddit). If I am mistaken or if the flairs are available anew, please, create another issue.

**Comment by TheGuywithTheHat** [comment]
Just FYI, flairs will be available at some point. It's just one of the features that hasn't been added to the redesign yet.
