### ISSUE TITLE
Comment footer/ending displays incorrectly

### ISSUE THREAD

**Issue by ErikHumphrey** [Jonarzz/DotaResponsesRedditBot#24]
![After](https://i.imgur.com/2lGPSOZ.jpg)

Probably has to be fixed in the properties file; can't find it here.

**Comment by Jonarzz** [comment]
Could you post a link to the comment? I checked a few footers and they look fine:
![image](https://user-images.githubusercontent.com/9656866/44251014-284e1500-a1f7-11e8-9a5b-0fafd7979566.png)
([link to the comment shown above](https://www.reddit.com/r/DotA2/comments/97jjmm/breaking_news_rick_and_morty_as_special_guests/e492jt4/))

**Comment by ErikHumphrey** [comment]
Sorry, seems to display for all recent comments, going back as far as a month. I don't use RES or any browser extensions. Your screenshot is from the Reddit redesign, though. The issue is not present on the redesign, but here's a link to one on the old design:  https://old.reddit.com/r/DotA2/comments/987i2z/the_international_8_group_stage_group_a_series_8/e4e3wzz/?context=3

Should I make issues for pre-redesign Reddit?

**Comment by Jonarzz** [comment]
All right, so it would seem that the redesigned Reddit has different markdown parsing than the pre-redesign version. Honestly I do not get on Reddit much nowadays and I was not even aware of the fact that there are two versions of the page. 

If you know a way to make the footer markdown consistent for both redesign and pre-redesign versions of the page, I will update the bot's footer message.

**Comment by ErikHumphrey** [comment]
There's an ongoing discussion of [markdown differences between new and old Reddit](https://www.reddit.com/r/redditdev/comments/981oe3/markdown_differences_between_new_and_old_reddit/), but I haven't dabbled enough with the Reddit API to test anything.

**Comment by MePsyDuck** [comment]
I tested same comment on both [old](https://old.reddit.com/r/test/comments/9tkwhc/test/) and [new](https://new.reddit.com/r/test/comments/9tkwhc/test/) reddit. There's no escaping needed for `_` in `Thanks iggys\_reddit\_account for the server!`. With `\` ,only new reddit renders it properly while it's broken for old reddit. Removing `\` fixes formatting in both.
