### ISSUE TITLE
Category link is possibly broken 

### ISSUE THREAD

**Issue by MePsyDuck** [Jonarzz/DotaResponsesRedditBot#26]
`CATEGORY = 'Lists of responses'` in file /responses_wiki/dota_wiki_parser.py is possibly broken. The full API request doesn't work because of this. This could be the reason the bot doesn't respond for Grimstroke responses.

Original request: `https://dota2.gamepedia.com/api.php?action=query&list=categorymembers&cmlimit=max&cmprop=title&format=json&cmtitle=Category:Lists_of_responses` returns nothing.

Possible fix: 
`CATEGORY = 'Responses'`
New request: `https://dota2.gamepedia.com/api.php?action=query&list=categorymembers&cmlimit=max&cmprop=title&format=json&cmtitle=Category:Responses`

**Comment by Jonarzz** [comment]
Thanks for the URL fix.

For Grimstroke responses to be working though, I will have to run `add_hero_specific_responses(["Grimstroke/Responses"])` from `dota_responses_database.py`, but at the moment I don't have the access to the server where the bot is running. I will update this issue, when the responses are added to the database.
