### ISSUE TITLE
Voice response should try to match OP's flair first

### ISSUE THREAD

**Issue by macabu** [Jonarzz/DotaResponsesRedditBot#3]
If possible to detect which flair the OP has, the Bot should try to find the responses within that hero's messages before, in case there is a duplicate message. Right now if that is the case, the first hero in alphabetical order will get its response sent instead.

**Comment by Jonarzz** [comment]
I will have to check if it doesn't significantly slow the bot. When I have some time, I will check it and if the difference isn't too big, I will leave the change.

**Comment by NNTin** [comment]
As an alternative:  
Bot can post multiple responses. [See picture](http://i.imgur.com/xsmBq1m.png)

**Comment by FlorianWendelborn** [comment]
@NNTin Shitty Wizard

**Comment by Jonarzz** [comment]
@NNTin The idea is really cool, but the number of responses differs from one to a few dozens, so it had to be controlled and also checked in all the heroes responses databases. Right now people complain that the bot is slow (about 15 minutes for a full run) and it would be much slower with your solution unfortunately.

**Comment by Jonarzz** [comment]
The code is up and running, but it needs testing on the subreddit. In case of any bugs or the feature not working, I will try to fix it as soon as possible.

**Comment by Jonarzz** [comment]
[Seems to be working.](https://www.reddit.com/r/DotA2/comments/4jc5io/meepo_girls_strike_back_as_phantom_lancer/d36331k)

**Comment by macabu** [comment]
Nice nice thanks mate
