### ISSUE TITLE
Force Voice Response From Specific Hero

### ISSUE THREAD

**Issue by FlorianWendelborn** [Jonarzz/DotaResponsesRedditBot#6]
Would be nice, if you'd allow users to do something like this:

```
Windranger: Not Gonna Happen
```

or

```
Not Gonna Happen (Windranger)
```

via [Reddit](https://www.reddit.com/r/DotA2/comments/4g2z0v/ee_my_ass_got_grabbed_multiple_times_not_good/d2e6nr4)

**Comment by Jonarzz** [comment]
I'm afraid that such a feature would be hardly used, but it would significantly slow the bot down (it's already taking the bot about 15 minutes to do a full run).
