### ISSUE TITLE
Hero icon in response comment

### ISSUE THREAD

**Issue by NNTin** [Jonarzz/DotaResponsesRedditBot#8]
Something like [this](http://i.imgur.com/CbkesQn.png).
Maybe [at the end](http://i.imgur.com/JlfuuB3.png) again if the sound warning message is needed.

These are all the standard hero flairs /r/dota2 uses: http://pastebin.com/pLTp4DRA ([Code](http://pastebin.com/B4L2CUPv))

This wouldn't work well if the bot is referencing announcers.

**Comment by Jonarzz** [comment]
Nice idea, I will try to add it when I create separate dictionaries for each hero. Thanks!

**Comment by Jonarzz** [comment]
[Done](https://www.reddit.com/r/DotA2/comments/4jbx95/spoiler_the_outcome_of_the_next_game_was_decided/d35c0w3), but needs testing. If there are bugs, I will fix them as soon as possible.

**Comment by NNTin** [comment]
https://www.reddit.com/r/DotA2/comments/4jh3k2/all_pick/d37fi0y

Wraith King works, Skeleton King does not.

**Comment by Jonarzz** [comment]
There is no Skeleton King icon on /r/DotA2 subreddit (correct me if I'm wrong). I'm not sure if users would like Wraith King flair displayed there (based on their comments under Skeleton King/Wraith King responses, calling SK better and original).
